In [72]:
##importing Api file from our file source
import requests
import pandas as pd

In [73]:
## calling for my api request
call=requests.get("https://v6.vbb.transport.rest/locations?query=berlin")

In [74]:
##checking for request status. 200= successful
call.status_code

200

In [75]:
##Exploring my Api file to show results of call
call.json()

[{'type': 'stop',
  'id': '900037168',
  'name': 'Berlin, Albrechtshof Bhf',
  'location': {'type': 'location',
   'id': '900037168',
   'latitude': 52.549339,
   'longitude': 13.129159},
  'products': {'suburban': False,
   'subway': False,
   'tram': False,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': True},
  'stationDHID': 'de:11000:900037168'},
 {'type': 'stop',
  'id': '900029305',
  'name': 'Berlin, Staaken Bhf',
  'location': {'type': 'location',
   'id': '900029305',
   'latitude': 52.537698,
   'longitude': 13.142157},
  'products': {'suburban': False,
   'subway': False,
   'tram': False,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': True},
  'stationDHID': 'de:11000:900029305'},
 {'type': 'stop',
  'id': '900180008',
  'name': 'Bahnhofstr./Lindenstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900180008',
   'latitude': 52.450916,
   'longitude': 13.572408},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900180008'},
 {'type': 'stop',
  'id': '900180009',
  'name': 'Bahnhofstr./Seelenbinderstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900180009',
   'latitude': 52.455761,
   'longitude': 13.577118},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900180009'},
 {'type': 'stop',
  'id': '900170011',
  'name': 'Barnimplatz (Berlin)',
  'location': {'type': 'location',
   'id': '900170011',
   'latitude': 52.567803,
   'longitude': 13.573694},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900170011'},
 {'type': 'stop',
  'id': '900170010',
  'name': 'Betriebshof Marzahn (Berlin)',
  'location': {'type': 'location',
   'id': '900170010',
   'latitude': 52.549006,
   'longitude': 13.583717},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900170010'},
 {'type': 'stop',
  'id': '900170524',
  'name': 'Brodowiner Ring (Berlin)',
  'location': {'type': 'location',
   'id': '900170524',
   'latitude': 52.54764,
   'longitude': 13.578359},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900170524'},
 {'type': 'stop',
  'id': '900171517',
  'name': 'Boschpoler Str. (Berlin)',
  'location': {'type': 'location',
   'id': '900171517',
   'latitude': 52.527504,
   'longitude': 13.548811},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900171517'},
 {'type': 'stop',
  'id': '900100041',
  'name': 'Brunnenstr./Invalidenstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900100041',
   'latitude': 52.532601,
   'longitude': 13.398889},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900100041'},
 {'type': 'stop',
  'id': '900140506',
  'name': 'Behaimstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900140506',
   'latitude': 52.54995,
   'longitude': 13.44628},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': False,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900140506'}]

In [76]:
##Exploring my data list  
call.json()[0]

{'type': 'stop',
 'id': '900037168',
 'name': 'Berlin, Albrechtshof Bhf',
 'location': {'type': 'location',
  'id': '900037168',
  'latitude': 52.549339,
  'longitude': 13.129159},
 'products': {'suburban': False,
  'subway': False,
  'tram': False,
  'bus': True,
  'ferry': False,
  'express': False,
  'regional': True},
 'stationDHID': 'de:11000:900037168'}

In [77]:
##checking for dictionary keys from call
call.json()[0].keys()

dict_keys(['type', 'id', 'name', 'location', 'products', 'stationDHID'])

In [78]:
call.json()

[{'type': 'stop',
  'id': '900037168',
  'name': 'Berlin, Albrechtshof Bhf',
  'location': {'type': 'location',
   'id': '900037168',
   'latitude': 52.549339,
   'longitude': 13.129159},
  'products': {'suburban': False,
   'subway': False,
   'tram': False,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': True},
  'stationDHID': 'de:11000:900037168'},
 {'type': 'stop',
  'id': '900029305',
  'name': 'Berlin, Staaken Bhf',
  'location': {'type': 'location',
   'id': '900029305',
   'latitude': 52.537698,
   'longitude': 13.142157},
  'products': {'suburban': False,
   'subway': False,
   'tram': False,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': True},
  'stationDHID': 'de:11000:900029305'},
 {'type': 'stop',
  'id': '900180008',
  'name': 'Bahnhofstr./Lindenstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900180008',
   'latitude': 52.450916,
   'longitude': 13.572408},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900180008'},
 {'type': 'stop',
  'id': '900180009',
  'name': 'Bahnhofstr./Seelenbinderstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900180009',
   'latitude': 52.455761,
   'longitude': 13.577118},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900180009'},
 {'type': 'stop',
  'id': '900170011',
  'name': 'Barnimplatz (Berlin)',
  'location': {'type': 'location',
   'id': '900170011',
   'latitude': 52.567803,
   'longitude': 13.573694},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900170011'},
 {'type': 'stop',
  'id': '900170010',
  'name': 'Betriebshof Marzahn (Berlin)',
  'location': {'type': 'location',
   'id': '900170010',
   'latitude': 52.549006,
   'longitude': 13.583717},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900170010'},
 {'type': 'stop',
  'id': '900170524',
  'name': 'Brodowiner Ring (Berlin)',
  'location': {'type': 'location',
   'id': '900170524',
   'latitude': 52.54764,
   'longitude': 13.578359},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900170524'},
 {'type': 'stop',
  'id': '900171517',
  'name': 'Boschpoler Str. (Berlin)',
  'location': {'type': 'location',
   'id': '900171517',
   'latitude': 52.527504,
   'longitude': 13.548811},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900171517'},
 {'type': 'stop',
  'id': '900100041',
  'name': 'Brunnenstr./Invalidenstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900100041',
   'latitude': 52.532601,
   'longitude': 13.398889},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': True,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900100041'},
 {'type': 'stop',
  'id': '900140506',
  'name': 'Behaimstr. (Berlin)',
  'location': {'type': 'location',
   'id': '900140506',
   'latitude': 52.54995,
   'longitude': 13.44628},
  'products': {'suburban': False,
   'subway': False,
   'tram': True,
   'bus': False,
   'ferry': False,
   'express': False,
   'regional': False},
  'stationDHID': 'de:11000:900140506'}]

In [79]:
##Assigning my result to a new value X 
X=call.json()

In [80]:
##importing results into my dataframe for more analysis
df=pd.DataFrame.from_records(X)

In [81]:
##Exploring five 5 information from the data set
df.head()

,type,id,name,location,products,stationDHID
0,stop,900037168,"Berlin, Albrechtshof Bhf","{'type': 'location', 'id': '900037168', 'latit...","{'suburban': False, 'subway': False, 'tram': F...",de:11000:900037168
1,stop,900029305,"Berlin, Staaken Bhf","{'type': 'location', 'id': '900029305', 'latit...","{'suburban': False, 'subway': False, 'tram': F...",de:11000:900029305
2,stop,900180008,Bahnhofstr./Lindenstr. (Berlin),"{'type': 'location', 'id': '900180008', 'latit...","{'suburban': False, 'subway': False, 'tram': T...",de:11000:900180008
3,stop,900180009,Bahnhofstr./Seelenbinderstr. (Berlin),"{'type': 'location', 'id': '900180009', 'latit...","{'suburban': False, 'subway': False, 'tram': T...",de:11000:900180009
4,stop,900170011,Barnimplatz (Berlin),"{'type': 'location', 'id': '900170011', 'latit...","{'suburban': False, 'subway': False, 'tram': T...",de:11000:900170011

In [82]:
##Extracting needed colunm for analysis then assigning the data to a new variable (newdf)
newdf=df[['type','id','name','stationDHID']]

In [85]:
newdf.head()

   type         id                                   name         stationDHID
0  stop  900037168               Berlin, Albrechtshof Bhf  de:11000:900037168
1  stop  900029305                    Berlin, Staaken Bhf  de:11000:900029305
2  stop  900180008        Bahnhofstr./Lindenstr. (Berlin)  de:11000:900180008
3  stop  900180009  Bahnhofstr./Seelenbinderstr. (Berlin)  de:11000:900180009
4  stop  900170011                   Barnimplatz (Berlin)  de:11000:900170011

In [83]:
##Extracting only the name to an empty list
name=[]

In [84]:
##Using the FOR loop to extract information into the empty list
for x in call.json():
    name.append(x['name'])
##print(name)
df_name=pd.DataFrame(name)##converting to a DataFrame

In [61]:
df_name

                                        0
0                Berlin, Albrechtshof Bhf
1                     Berlin, Staaken Bhf
2         Bahnhofstr./Lindenstr. (Berlin)
3   Bahnhofstr./Seelenbinderstr. (Berlin)
4                    Barnimplatz (Berlin)
5            Betriebshof Marzahn (Berlin)
6                Brodowiner Ring (Berlin)
7                Boschpoler Str. (Berlin)
8      Brunnenstr./Invalidenstr. (Berlin)
9                     Behaimstr. (Berlin)
10               Berlin, Albrechtshof Bhf
11                    Berlin, Staaken Bhf
12        Bahnhofstr./Lindenstr. (Berlin)
13  Bahnhofstr./Seelenbinderstr. (Berlin)
14                   Barnimplatz (Berlin)
15           Betriebshof Marzahn (Berlin)
16               Brodowiner Ring (Berlin)
17               Boschpoler Str. (Berlin)
18     Brunnenstr./Invalidenstr. (Berlin)
19                    Behaimstr. (Berlin)

In [64]:
##Using the FOR loop to extract information into the empty list
longitude=[]
for x in call.json():
    longitude.append(x['location']['longitude'])
print(longitude)

[13.129159, 13.142157, 13.572408, 13.577118, 13.573694, 13.583717, 13.578359, 13.548811, 13.398889, 13.44628]

In [65]:
##Using the FOR loop to extract information into the empty list
latitude=[]
for x in call.json():
    latitude.append(x['location']['latitude'])
print(latitude)

[52.549339, 52.537698, 52.450916, 52.455761, 52.567803, 52.549006, 52.54764, 52.527504, 52.532601, 52.54995]

In [68]:
##Using the FOR loop to extract information into the empty list
products=[]
for x in call.json():
    products.append(x['products'])
#print(products)
df_products=pd.DataFrame(products)##converting to a DataFrame

In [69]:
df_products

   suburban  subway   tram    bus  ferry  express  regional
0     False   False  False   True  False    False      True
1     False   False  False   True  False    False      True
2     False   False   True   True  False    False     False
3     False   False   True   True  False    False     False
4     False   False   True   True  False    False     False
5     False   False   True   True  False    False     False
6     False   False   True   True  False    False     False
7     False   False   True   True  False    False     False
8     False   False   True   True  False    False     False
9     False   False   True  False  False    False     False

In [88]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   type         10 non-null     object
 1   id           10 non-null     object
 2   name         10 non-null     object
 3   stationDHID  10 non-null     object
dtypes: object(4)
memory usage: 452.0+ bytes

In [90]:
newdf.to_csv("ExtractedApifile.csv")